

package UserInterface.AdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  truptiraut
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    Organization organization;
    UserAccount account;
    EcoSystem business;
     Network network;
    /** Creates new form AdminWorkAreaJPanel */
  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount account, EcoSystem business, Network network) {
         initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = business;
        this.account = account;
        this.network =network;
        valueLabel.setText(enterprise.getName());
        if(enterprise.getEnterpriseType().toString().equals("Store Unit")){
            ManageReq.setVisible(false);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageEmp = new javax.swing.JButton();
        ManageOrg = new javax.swing.JButton();
        ManageReq = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 201, 174));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageEmp.setBackground(new java.awt.Color(255, 255, 255));
        ManageEmp.setFont(new java.awt.Font("PT Serif Caption", 1, 18)); // NOI18N
        ManageEmp.setText("Manage Employee");
        ManageEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEmpActionPerformed(evt);
            }
        });
        add(ManageEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 280, 90));

        ManageOrg.setBackground(new java.awt.Color(255, 255, 255));
        ManageOrg.setFont(new java.awt.Font("PT Serif Caption", 1, 18)); // NOI18N
        ManageOrg.setText("Manage Organization");
        ManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageOrgActionPerformed(evt);
            }
        });
        add(ManageOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 280, 100));

        ManageReq.setBackground(new java.awt.Color(255, 255, 255));
        ManageReq.setFont(new java.awt.Font("PT Serif Caption", 1, 18)); // NOI18N
        ManageReq.setText("Manage Requests");
        ManageReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageReqActionPerformed(evt);
            }
        });
        add(ManageReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 280, 90));

        jPanel3.setBackground(new java.awt.Color(214, 177, 147));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(80, 80, 82));
        enterpriseLabel.setText("Enterprise :");
        jPanel3.add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 120, 30));

        valueLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(80, 80, 82));
        valueLabel.setText("<value>");
        jPanel3.add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 260, 30));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEmpActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),business);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_ManageEmpActionPerformed

    private void ManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrgActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageOrgActionPerformed

    private void ManageReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageReqActionPerformed
        ManageRequestsJPanel manageRequestsJPanel = new ManageRequestsJPanel(userProcessContainer, enterprise, account, organization, business);
        userProcessContainer.add("manageRequestsJPanel", manageRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_ManageReqActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEmp;
    private javax.swing.JButton ManageOrg;
    private javax.swing.JButton ManageReq;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
