/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author truptiraut
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
      
    JPanel userProcessContainer;
    Enterprise enterprise;
    Organisation organisation;
    UserAccount account;
    EcoSystem business;
     Network network;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
     public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organisation organisation, UserAccount account, EcoSystem business, Network network) {
         initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organisation = organisation;
        this.business = business;
        this.account = account;
        this.network =network;
       // greetLbl.setText(account.getEmployee().getName()+ "!!");
        ValLable.setText(enterprise.getName());
        if(enterprise.getEnterpriseType().toString().equals("Store Unit")){
            ManageReq.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ValLable = new javax.swing.JLabel();
        ManageOrg = new javax.swing.JButton();
        ManageEmp = new javax.swing.JButton();
        ManageReq = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enterprise");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        ValLable.setText("value");
        add(ValLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        ManageOrg.setText("Manage Organisation");
        ManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageOrgActionPerformed(evt);
            }
        });
        add(ManageOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        ManageEmp.setText("Manage Employee");
        ManageEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEmpActionPerformed(evt);
            }
        });
        add(ManageEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        ManageReq.setText("Manage Requests");
        ManageReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageReqActionPerformed(evt);
            }
        });
        add(ManageReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrgActionPerformed
        // TODO add your handling code here:
        ManageOrganisationJPanel manageOrganizationJPanel = new ManageOrganisationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageOrgActionPerformed

    private void ManageEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEmpActionPerformed
        // TODO add your handling code here:
         ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganisationDirectory(),business);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageEmpActionPerformed

    private void ManageReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageReqActionPerformed
        // TODO add your handling code here:
         ManageRequestsJPanel manageRequestsJPanel = new ManageRequestsJPanel(userProcessContainer, enterprise, account, organisation, business);
        userProcessContainer.add("manageRequestsJPanel", manageRequestsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_ManageReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEmp;
    private javax.swing.JButton ManageOrg;
    private javax.swing.JButton ManageReq;
    private javax.swing.JLabel ValLable;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
