/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import Business.Enterprise.Enterprise;
import Business.Organisation.Organisation;
import Business.Organisation.Organisation.Type;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author truptiraut
 */
public class ManageOrganisationJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private Enterprise enterprise;

    /**
     * Creates new form ManageOrganisationJPanel
     */
     public ManageOrganisationJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
       // organizationJTable.getTableHeader().setDefaultRenderer(new tableHeaderColors());
        populateTable();
        populateComboBox();
    }
      private void populateComboBox(){
          
        OrgComboBox.removeAllItems();
        String ent = enterprise.getEnterpriseType().toString();
         for (Type type : Organisation.Type.values()){
             //String t=type.toString()
              //String o=type.toString();
            if(ent.equals("Grocery Store Unit")){
                 if (type.getValue().equals(Type.GroceryStore.getValue())){
                    OrgComboBox.addItem(type.getValue());
                }
            }else if(ent.equals("Community Fridge Unit")){
                 if (type.getValue().equals(Type.CommunityFridge.getValue())){
                    OrgComboBox.addItem(type.getValue());
                }
               
            }
            else if(ent.equals("Transport Unit")){
                 if (type.getValue().equals(Type.DeliveryMan.getValue())){
                    OrgComboBox.addItem(type.getValue());
                }
              
                 
            }
            else if(ent.equals("Quality Assurance Unit")){
                 if (type.getValue().equals(Type.FoodAdvisor.getValue())){
                    OrgComboBox.addItem(type.getValue());
                }
                if (type.getValue().equals(Type.FoodSafetyOfficer.getValue())){
                    OrgComboBox.addItem(type.getValue());
                } 
            }
         }
         
    }
       private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) OrgTable.getModel();
        
        model.setRowCount(0);
        //System.out.println(Network);
        
        for (Organisation organisation : enterprise.getOrganisationDirectory().getOrganisationList()){
            Object[] row = new Object[2];
            row[0] = organisation.getOrganisationID();
            row[1] = organisation.getName();
            
            model.addRow(row);
        }
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrgTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        OrgComboBox = new javax.swing.JComboBox<>();
        Add = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        OrgTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(OrgTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 430, 200));

        jLabel1.setText("Organisation Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        OrgComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(OrgComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
         Type type = (Type) OrgComboBox.getSelectedItem();
        String t = String.valueOf(type)+" Organization";
        for(Organisation org: enterprise.getOrganisationDirectory().getOrganisationList()){   
            if(org.getName().equals(t)){
                JOptionPane.showMessageDialog(null, "Organization is already added !","Alert",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        enterprise.getOrganisationDirectory().createOrganisation(type);
        populateTable();
    }//GEN-LAST:event_AddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> OrgComboBox;
    private javax.swing.JTable OrgTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
