/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import java.time.Clock;
import static java.time.Clock.system;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author visha
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateTable();
        populateCombo();
    }
    
    private void populateCombo(){
        OrgCB.removeAllItems();
        String ent = enterprise.getEnterpriseType().toString();
         for (Type type : Organization.Type.values()){
            if(ent.equals("CommunityFridge")){
                 if (type.getValue().equals(Type.CommunityFridge.getValue())){
                    OrgCB.addItem(type);
                }
            }else if(ent.equals("Volunteer")){
                 if (type.getValue().equals(Type.DonationOrganization.getValue())){
                    OrgCB.addItem(type);
                }
                if (type.getValue().equals(Type.EventOrganization.getValue())){
                    OrgCB.addItem(type);
                }
                 
            }
            else if(ent.equals("QualityAssurance")){
                 if (type.getValue().equals(Type.FoodAdvisorOrganisation.getValue())){
                    OrgCB.addItem(type);
                }
                if (type.getValue().equals(Type.FoodSafetyOrganization.getValue())){
                    OrgCB.addItem(type);
                }
              
                 
            }
            else if(ent.equals("GroceryStoreUnit")){
                 if (type.getValue().equals(Type.GroceryStoreOrganization.getValue())){
                    OrgCB.addItem(type);
                }
                if (type.getValue().equals(Type.Delivery.getValue())){
                    OrgCB.addItem(type);
                } 
            }
         }
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) OrgTable.getModel();
        model.setRowCount(0);        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrgTable = new javax.swing.JTable();
        add = new javax.swing.JButton();
        OrgCB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OrgTable.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        OrgTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OrgTable);
        if (OrgTable.getColumnModel().getColumnCount() > 0) {
            OrgTable.getColumnModel().getColumn(0).setResizable(false);
            OrgTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 91, 480, 92));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 303, 122, 42));

        OrgCB.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        OrgCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        OrgCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrgCBActionPerformed(evt);
            }
        });
        add(OrgCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 190, 30));

        jLabel1.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        jLabel1.setText("Organization Type :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 231, -1, -1));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        Type type = (Type) OrgCB.getSelectedItem();
        String t = String.valueOf(type)+" Organization";
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){   
            if(org.getName().equals(t)){
                JOptionPane.showMessageDialog(null, "Organization is added earlier !","Alert",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        enterprise.getOrganizationDirectory().createOrganization(type);
        populateTable();
        
       
    }//GEN-LAST:event_addActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backActionPerformed

    private void OrgCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrgCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrgCBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox OrgCB;
    private javax.swing.JTable OrgTable;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
