/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CommunityFridge;


import Business.Receiver.Receiver;
import Business.Receiver.ReceiverDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CommunityFridgeOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CommunityFridgeWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author truptiraut
 */
public class CommunityFridgeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityFridgeWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    CommunityFridgeOrganization nutritionOrganisation;
    Enterprise enterprise;
    EcoSystem ecosystem;
    Network network;

    public CommunityFridgeWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount account, EcoSystem business, Network network) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
         this.account = account;
         this.enterprise = enterprise;
         this.ecosystem = business;
         this.network = network;
         populateRec();
         
    }
    
    
    public void populateRec(){
        DefaultTableModel dtm = (DefaultTableModel) RecTable.getModel();
        dtm.setRowCount(0);
        
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
        for(Employee emp : org.getEmployeeDirectory().getEmployeeList()){
            if(emp.toString().equals(account.getEmployee().toString())){
                for( WorkRequest request: account.getWorkQueue().getWorkRequestList()){
                Receiver rec = request.getSender().getReceiver();
            
            Object[] row = new Object[4];
            row[0] = rec.getId();
            row[1] = rec;
            row[2] = request;
            row[3] = request.getStatus();
            dtm.addRow(row);
           }
            }
        }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RecTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Approved = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        View = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Feedback = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RecTable.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        RecTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " ID", " Name", "Request", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RecTable);
        if (RecTable.getColumnModel().getColumnCount() > 0) {
            RecTable.getColumnModel().getColumn(0).setResizable(false);
            RecTable.getColumnModel().getColumn(1).setResizable(false);
            RecTable.getColumnModel().getColumn(2).setResizable(false);
            RecTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 675, 91));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 82));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Person Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 40, 1209, 39));

        Approved.setBackground(new java.awt.Color(255, 102, 0));
        Approved.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        Approved.setText("Approved");
        Approved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApprovedActionPerformed(evt);
            }
        });
        add(Approved, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 179, 45));

        NameField.setEditable(false);
        NameField.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 150, 30));

        jLabel2.setFont(new java.awt.Font("PT Serif Caption", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 107, 30));

        View.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        View.setText("View ");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        add(View, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 138, 45));

        jLabel3.setFont(new java.awt.Font("PT Serif Caption", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Write Reply:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, 70));

        Feedback.setColumns(20);
        Feedback.setRows(5);
        jScrollPane2.setViewportView(Feedback);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tomatoes.jpeg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void ApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApprovedActionPerformed
        // TODO add your handling code here:
        int selectedRow = RecTable.getSelectedRow();
        if(selectedRow >=0){
            Receiver rec = (Receiver) RecTable.getValueAt(selectedRow, 1);
            CommunityFridgeWorkRequest request = (CommunityFridgeWorkRequest) RecTable.getValueAt(selectedRow, 2);
            if(!"Request Accepted".equals(request.getStatus())){
                request.setCFResult(Feedback.getText());
                request.setStatus("Request Accepted");
                populateRec();
                JOptionPane.showMessageDialog(null,"Request Accepted!","Success",JOptionPane.INFORMATION_MESSAGE);
                Feedback.setText("");
           
     
            }else{
                
          
            JOptionPane.showMessageDialog(null,"Please Select a row","Error",JOptionPane.ERROR_MESSAGE);
        }
        }  
    }//GEN-LAST:event_ApprovedActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = RecTable.getSelectedRow();
        if(selectedRow >=0){
             Receiver customer = (Receiver) RecTable.getValueAt(selectedRow, 1);
           NameField.setText(customer.getName());
            
        }else{
            JOptionPane.showMessageDialog(null,"Please Select a row","Error",JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_ViewActionPerformed

    public void sendEmail(String email, String chart){
                
		final String password = "ThankyouMail@12345";
		String fromEmail = "thankyou@gmail.com";
		String toEmail = email;
		Properties properties = new Properties();
		properties.put("mail.smtp.auth", "true");
                properties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
		properties.put("mail.smtp.starttls.enable", "true");
		properties.put("mail.smtp.host", "smtp.gmail.com");
		properties.put("mail.smtp.port", "587");
		
		Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(fromEmail,password);
			}
		});
		MimeMessage msg = new MimeMessage(session);
		try {
			msg.setFrom(new InternetAddress(fromEmail));
			msg.addRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));
			msg.setSubject("Thankyou");
			Multipart emailContent = new MimeMultipart();
			MimeBodyPart textBodyPart = new MimeBodyPart();
			emailContent.addBodyPart(textBodyPart);
			msg.setContent(emailContent);
			Transport.send(msg);
			System.out.println("Sent message");
		}catch (MessagingException e) {
			e.printStackTrace();
		}
        // TODO Auto-generated catch block
         

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Approved;
    private javax.swing.JTextArea Feedback;
    private javax.swing.JTextField NameField;
    private javax.swing.JTable RecTable;
    private javax.swing.JButton View;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
