/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DonationManagerRole;


import Business.Receiver.Receiver;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CommunityFridgeOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author truptiraut
 */
public class DonationWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonationWorkAreaJPanel
     */   
    JPanel userProcessContainer;
    UserAccount account;
    CommunityFridgeOrganization nutritionOrganisation;
    Enterprise enterprise;
    EcoSystem ecosystem;
    Network network;
    public DonationWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount account, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
         this.account = account;
         this.enterprise = enterprise;
         this.ecosystem = business;
         this.network = network;
         populateReqs();
    }
    
    public void populateReqs(){
        DefaultTableModel dtm = (DefaultTableModel) ReqTable.getModel();
        dtm.setRowCount(0);
        
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
        for(Employee emp : org.getEmployeeDirectory().getEmployeeList()){
            if(emp.toString().equals(account.getEmployee().toString())){
                for( WorkRequest request: account.getWorkQueue().getWorkRequestList()){
                Receiver cust = request.getSender().getReceiver();
            
            Object[] row = new Object[4];
            row[0] = cust.getId();
            row[1] = cust;
            row[2] = request;
            row[3] = request.getStatus();
            dtm.addRow(row);
           }
            }
        }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ReqTable = new javax.swing.JTable();
        Accept = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Show = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Reply = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(109, 180, 176));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReqTable.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        ReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " ID", " Name", "Request", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ReqTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 675, 91));

        Accept.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Accept.setText("Approve");
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });
        add(Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 440, 300, 40));

        jLabel2.setFont(new java.awt.Font("PT Serif Caption", 1, 26)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 300, 200, 30));

        Name.setEditable(false);
        Name.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 160, 40));

        Show.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        Show.setText("View Details");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 240, 290, 45));

        jLabel1.setFont(new java.awt.Font("PT Serif Caption", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INTERESTED PERSON DETAILS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 40, 1200, 39));

        Reply.setColumns(20);
        Reply.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        Reply.setRows(5);
        jScrollPane2.setViewportView(Reply);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("PT Serif Caption", 1, 26)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Message:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 170, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foodDonation.jpeg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 680));
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
       int selectedRow = ReqTable.getSelectedRow();
        if(selectedRow >=0){
            DonationWorkRequest request = (DonationWorkRequest) ReqTable.getValueAt(selectedRow, 2);
            if(!"Result Posted".equals(request.getStatus())){
                request.setStatus("Accepted");
                request.setDonationResult(Reply.getText());
                populateReqs();
                JOptionPane.showMessageDialog(null,"Request Approved!","Success",JOptionPane.INFORMATION_MESSAGE);
                Reply.setText("");
            }else{
                JOptionPane.showMessageDialog(null,"Result has been already Processed","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Please Select a row","Error",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptActionPerformed

    
        // TODO Auto-generated catch block
         

    
    
    
    
    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        // TODO add your handling code here:
        int selectedRow = ReqTable.getSelectedRow();
        if(selectedRow >=0){
            Receiver customer = (Receiver) ReqTable.getValueAt(selectedRow, 1);
            Name.setText(customer.getName());
           
        }else{
            JOptionPane.showMessageDialog(null,"Please Select a row","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ShowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JTextField Name;
    private javax.swing.JTextArea Reply;
    private javax.swing.JTable ReqTable;
    private javax.swing.JButton Show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    
}
