/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodAdvisor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Receiver.Receiver;
import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Organization.FoodAdvisorOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodAdvisorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashwin
 */
public class FoodAdvisorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PhysioWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    EcoSystem ecosystem;
    Network network;

    public FoodAdvisorWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount account, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
         this.account = account;
         this.enterprise = enterprise;
         this.ecosystem = business;
         this.network = network;
         populateRec();
        
    }
    
    public void populateRec(){
        DefaultTableModel dtm = (DefaultTableModel) RecList.getModel();
        dtm.setRowCount(0);
        
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
        for(Employee emp : org.getEmployeeDirectory().getEmployeeList()){
            if(emp.toString().equals(account.getEmployee().toString())){
                for( WorkRequest request: account.getWorkQueue().getWorkRequestList()){
                Receiver cust = request.getSender().getReceiver();
            
            Object[] row = new Object[4];
            row[0] = cust.getId();
            row[1] = cust;
            row[2] = request;
            row[3] = request.getStatus();
            dtm.addRow(row);
           }
            }
        }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RecList = new javax.swing.JTable();
        Send = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        View = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reply = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RecList.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        RecList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " ID", " Name", "Advise", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RecList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 675, 91));

        Send.setBackground(new java.awt.Color(255, 255, 255));
        Send.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        Send.setText("Reply");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });
        add(Send, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 340, 40));

        jLabel2.setFont(new java.awt.Font("PT Serif Caption", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 107, 30));

        Name.setEditable(false);
        Name.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 190, 30));

        View.setBackground(new java.awt.Color(255, 255, 255));
        View.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        View.setText("View Details");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        add(View, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 220, 340, 45));

        jLabel1.setFont(new java.awt.Font("PT Serif Caption", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Receiver Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1209, 39));

        jLabel3.setFont(new java.awt.Font("PT Serif Caption", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Message:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 160, 30));

        reply.setColumns(20);
        reply.setRows(5);
        jScrollPane2.setViewportView(reply);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foodadv.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1590, 980));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = RecList.getSelectedRow();
        if(selectedRow >=0){
            Receiver customer = (Receiver) RecList.getValueAt(selectedRow, 1);
            Name.setText(customer.getName());
           
        }else{
            JOptionPane.showMessageDialog(null,"Please Select a row","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ViewActionPerformed

   

    
    
    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        int selectedRow = RecList.getSelectedRow();
        if(selectedRow >=0){
            FoodAdvisorWorkRequest request = (FoodAdvisorWorkRequest) RecList.getValueAt(selectedRow, 2);
            if(!"Result Posted".equals(request.getStatus())){
                request.setStatus("Request Accepted");
                request.setFoodadvresult(reply.getText());
                String name = account.getEmployee().getName();
                populateRec();
                JOptionPane.showMessageDialog(null,"Accepted!","Success",JOptionPane.INFORMATION_MESSAGE);
                reply.setText("");
            }else{
                JOptionPane.showMessageDialog(null,"Result has been already Processed","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Please Select a row","Error",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JTable RecList;
    private javax.swing.JButton Send;
    private javax.swing.JButton View;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea reply;
    // End of variables declaration//GEN-END:variables
}
