/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DonationManager;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DonationOrganisation;
import Business.Organisation.Organisation;
import static Business.Organisation.Organisation.Type.Receiver;
import Business.Receiver.Receiver;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonationManagerWorkRequest;
import Business.WorkQueue.FoodAdvWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author truptiraut
 */
public class DonationManagerWorkAreaJPanel extends javax.swing.JPanel {
     JPanel userProcessContainer;
    UserAccount account;
    DonationOrganisation donationOrganisation;
    Enterprise enterprise;
    EcoSystem system;
    Network network;

    public DonationManagerWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organisation organisation, UserAccount account, EcoSystem system, Network network) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
         this.account = account;
         this.enterprise = enterprise;
         this.system = system;
         //greetLbl.setText(account.getEmployee().getName() + "!!");
        // requestList.getTableHeader().setDefaultRenderer(new tableHeaderColors());
         this.network = network;
         populateRequests();
         
    }

    /**
     * Creates new form DonationManagerWorkAreaJPanel
     */
     public void populateRequests(){
        DefaultTableModel dtm = (DefaultTableModel) requestList.getModel();
        dtm.setRowCount(0);
        
        for(Organisation org: enterprise.getOrganisationDirectory().getOrganisationList()){
        for(Employee emp : org.getEmployeeDirectory().getEmployeeList()){
            if(emp.toString().equals(account.getEmployee().toString())){
                for( WorkRequest request: account.getWorkQueue().getWorkRequestList()){
                Receiver rec = request.getSender().getReceiver();
            
            Object[] row = new Object[4];
            row[0] = rec.getId();
            row[1] = rec;
            row[2] = request;
            row[3] = request.getStatus();
            dtm.addRow(row);
           }
            }
        }
        }
        
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestList = new javax.swing.JTable();
        Accept = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Msg = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Volunteer Request Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 42, -1, -1));

        requestList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "MESSAGE", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(requestList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 106, 533, 168));

        Accept.setText("Accept");
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });
        add(Accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 365, -1, -1));

        jLabel2.setText("Message");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 370, -1, -1));

        Msg.setColumns(20);
        Msg.setRows(5);
        jScrollPane2.setViewportView(Msg);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 365, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        // TODO add your handling code here:
          int selectedRow = requestList.getSelectedRow();
        if(selectedRow >=0){
            DonationManagerWorkRequest request = (DonationManagerWorkRequest) requestList.getValueAt(selectedRow, 2);
            if(!"Result Posted".equals(request.getStatus())){
                request.setStatus("Result Posted");
                request.setDonationResult(Msg.getText());
                String email = request.getSender().getUsername();
                String name = account.getEmployee().getName();
                //sendEmail(email, name);
                populateRequests();
                JOptionPane.showMessageDialog(null,"Email has been sent to Customer!","Success",JOptionPane.INFORMATION_MESSAGE);
                Msg.setText("");
            }else{
                JOptionPane.showMessageDialog(null,"Result has been already Processed","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Please Select a row","Error",JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_AcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JTextArea Msg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable requestList;
    // End of variables declaration//GEN-END:variables
}
