/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SysAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author truptiraut
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    EcoSystem system;
    Organisation organisation;
    Enterprise enterprise;
    UserAccount account;
    Network network;



    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organisation organisation, UserAccount account, EcoSystem system, Network network) {
       initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system= system;
        this.organisation = organisation;
        this.enterprise = enterprise;
        this.account = account;
        this.network = network;
//        greetLbl.setText(account.getEmployee().getName() + "!!");
        populateTree();
    }
    
     public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)jTree1.getModel();
        ArrayList<Network> networkList=system.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organisation> organisationList;
        
        Network network;
        Enterprise enterprise;
        Organisation organisation;
        
        DefaultMutableTreeNode networks=new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organisationNode;
        
        for(int i=0;i<networkList.size();i++){
            network=networkList.get(i);
            networkNode=new DefaultMutableTreeNode(network.getName());
            networks.insert(networkNode, i);
            
            enterpriseList=network.getEnterpriseDirectory().getEnterpriseList();
            for(int j=0; j<enterpriseList.size();j++){
                enterprise=enterpriseList.get(j);
                enterpriseNode=new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);
                
                organisationList=enterprise.getOrganisationDirectory().getOrganisationList();
                for(int k=0;k<organisationList.size();k++){
                    organisation=organisationList.get(i);
                    organisationNode=new DefaultMutableTreeNode(organisation.getName());
                    enterpriseNode.insert(organisationNode, k);
                }
            }
        }
        model.reload();
    }
    
  


    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel3 = new javax.swing.JLabel();
        nodeselected = new javax.swing.JLabel();
        ManageNetwork = new javax.swing.JButton();
        ManageEnterprise = new javax.swing.JButton();
        ManageEntAdmins = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(215, 200, 174));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jTree1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 270));

        jLabel3.setText("selected node:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        nodeselected.setText("value");
        add(nodeselected, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        ManageNetwork.setText("Manage Network");
        ManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageNetworkActionPerformed(evt);
            }
        });
        add(ManageNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 169, -1, 50));

        ManageEnterprise.setText("Manage All Enterprise");
        ManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEnterpriseActionPerformed(evt);
            }
        });
        add(ManageEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, 50));

        ManageEntAdmins.setText("Manage Enterprise Admins");
        ManageEntAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEntAdminsActionPerformed(evt);
            }
        });
        add(ManageEntAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tomatoes.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -300, 2220, 1980));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageNetworkActionPerformed
        // TODO add your handling code here:
         ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageNetworkActionPerformed

    private void ManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEnterpriseActionPerformed
        // TODO add your handling code here:
         ManageEnterpriseJPanel manageEnterpriseJPanel=new ManageEnterpriseJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageEnterpriseActionPerformed

    private void ManageEntAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEntAdminsActionPerformed
        // TODO add your handling code here:
         ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel=new ManageEnterpriseAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterpriseAdminJPanel",manageEnterpriseAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageEntAdminsActionPerformed
      private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {                                   
        
        DefaultMutableTreeNode selectedNode= (DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
        if(selectedNode!=null){
            nodeselected.setText(selectedNode.toString());
        }
    }   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEntAdmins;
    private javax.swing.JButton ManageEnterprise;
    private javax.swing.JButton ManageNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel nodeselected;
    // End of variables declaration//GEN-END:variables

        }
