/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GroceryStoreManagerRole;

import UserInterface.Transport.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.Organisation;
import Business.Receiver.ReceiverRequest;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GroceryManagerWorkRequest;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author truptiraut
 */
public class DeliveryPersonAssignJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private ReceiverRequest order;
    private EcoSystem system;
    private GroceryManagerWorkRequest request;


    /**
     * Creates new form DeliveryPersonAssignJPanel
     */
    DeliveryPersonAssignJPanel(JPanel userProcessContainer, EcoSystem system, Enterprise enterprise, GroceryManagerWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system=system;
        this.request = request;
        this.enterprise = enterprise;
        populateComboBox();
    }

     private void populateComboBox() {
        DefaultComboBoxModel dm=new DefaultComboBoxModel();
           for(Organisation o:enterprise.getOrganisationDirectory().getOrganisationList()){
                for(UserAccount e : o.getUserAccountDirectory().getUserAccountList()){
                    if(e.getRole().toString().equals("Business.Role.DeliveryManRole")){
                        dm.addElement(e.getEmployee().getName());
                        DeliveryPeople.setModel(dm);
                    }
                }
             }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DeliveryPeople = new javax.swing.JComboBox<>();
        Assign = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        jLabel1.setText("Assign DeliveryMan");

        jLabel2.setText("Delivery Man");

        DeliveryPeople.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Assign.setText("Assign");
        Assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(DeliveryPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(Assign))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Back)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DeliveryPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(Assign)
                .addGap(97, 97, 97)
                .addComponent(Back)
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignActionPerformed
        // TODO add your handling code here:
        for(Organisation org: enterprise.getOrganisationDirectory().getOrganisationList()){
            for(UserAccount user: org.getUserAccountDirectory().getUserAccountList()){
            if(DeliveryPeople.getSelectedItem().equals(user.getEmployee().getName())){    
                request.setReceiver(user);
                request.setStatus("Deliverman Assigned");
                user.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "Delivery Person assigned successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        }
    }//GEN-LAST:event_AssignActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assign;
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> DeliveryPeople;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
