/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GroceryStoreManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Products;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashwin
 */
public class ManagerStockJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private UserAccount userAcc;
    private EcoSystem system;
    private Organisation organisation;
    private Enterprise enterprise;
    private UserAccount account;
    
   


    /**
     * Creates new form ManagerStockJPanel
     */
    public ManagerStockJPanel(JPanel userProcessContainer, Organisation organisation, EcoSystem system, Enterprise enterprise, UserAccount account) {
       initComponents();
        this.organisation=organisation;
         this.system=system;
        this.enterprise=enterprise;
        this.account=account;
      
        this.userProcessContainer=userProcessContainer;
                populateTable();
    }
    
    
    
      private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) ProductTable.getModel();
        dtm.setRowCount(0);
      
        for(Products store:enterprise.getProductsList()) {
            Object row[] = new Object[3];
            row[0] = store;
            row[1] = store.getProductType();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ProductNameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DateField = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Manage Stock");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 34, -1, -1));

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Name", "Product Type", "Expiry Date"
            }
        ));
        jScrollPane1.setViewportView(ProductTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 95, 405, 175));

        jLabel2.setText("Product Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 317, -1, -1));

        ProductNameText.setText("jTextField1");
        add(ProductNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 312, -1, -1));

        jLabel3.setText("Date");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 361, -1, -1));

        DateField.setText("jTextField2");
        add(DateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 356, -1, -1));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 409, -1, -1));

        Delete.setText("Delete Product");
        add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 456, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        
            
            for(Products item:enterprise.getProductsList()) {
            if(ProductNameText.getText().equals(item.getProductName())){
                
        JOptionPane.showMessageDialog(null, "Product already exists.","Error",JOptionPane.ERROR_MESSAGE);
        return;
            } 
        
        if(ProductNameText.getText().equals("")||ProductNameText.getText()==null){
              JOptionPane.showMessageDialog(null, "Field should not be empty.","Error",JOptionPane.ERROR_MESSAGE);
        return;
        }
       
       
        
        String name = ProductNameText.getText();
//        String type = (String) typeComboBox.getSelectedItem();
//       Date date = DateField.getText();
 //Date date=new SimpleDateFormat("dd/MM/yyyy").parse();  
        Products p = enterprise.createMenuItem();
        p.setProductName(name);
      
       // p.setExpires(date);
        JOptionPane.showMessageDialog(null, "Item Added Successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
        populateTable();
        ProductNameText.setText("");
        
                
//        
            }
    }//GEN-LAST:event_AddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField DateField;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField ProductNameText;
    private javax.swing.JTable ProductTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
