/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GroceryStoreManager;


import Business.EcoSystem;
import Business.ReceiverRequestOrder;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import static Business.Role.Role.RoleType.DeliveryMan;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CommunityFridgeWorkRequest;
import Business.WorkQueue.GroceryStoreWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashwin
 */
public class DeliveryManAssignJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ReceiverRequestOrder order;
    private EcoSystem business;
    private Enterprise enterprise;
    private GroceryStoreWorkRequest request;

    /**
     * Creates new form DeliveryManAssignJPanel
     */

    DeliveryManAssignJPanel(JPanel userProcessContainer, EcoSystem business, Enterprise enterprise, GroceryStoreWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business=business;
        this.request = request;
        this.enterprise = enterprise;
        populateComboBox();
    }
    private void populateComboBox() {
        DefaultComboBoxModel dm=new DefaultComboBoxModel();
           for(Organization o:enterprise.getOrganizationDirectory().getOrganizationList()){
                for(UserAccount e : o.getUserAccountDirectory().getUserAccountList()){
                    if(e.getRole().toString().equals("Business.Role.DeliveryManRole")){
                        dm.addElement(e.getEmployee().getName());
                        DeliveryMan.setModel(dm);
                    }
                }
             }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DeliveryMan = new javax.swing.JComboBox<>();
        Assign = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("PT Serif Caption", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 82));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Assign Deliveryman");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 340, 50));

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        Back.setText(" Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 82, 37));

        jLabel3.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Deliveryman:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 151, -1));

        DeliveryMan.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        DeliveryMan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(DeliveryMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 150, 30));

        Assign.setBackground(new java.awt.Color(255, 255, 255));
        Assign.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        Assign.setText("Assign");
        Assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignActionPerformed(evt);
            }
        });
        add(Assign, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 140, 30));

        jLabel2.setBackground(new java.awt.Color(243, 223, 198));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/beige.jpeg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, 0, 1550, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackActionPerformed

    private void AssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignActionPerformed
        // TODO add your handling code here:
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
            for(UserAccount user: org.getUserAccountDirectory().getUserAccountList()){
            if(DeliveryMan.getSelectedItem().equals(user.getEmployee().getName())){    
                request.setReceiver(user);
                request.setStatus("Delivery man Assigned");
                user.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "Delivery man assigned successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
        }
            }
        
        }
    }//GEN-LAST:event_AssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assign;
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> DeliveryMan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

     }