/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GroceryStoreManager;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Products;
import Business.Organization.Organization;
import Business.GroceryStore.GroceryStore;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashwin
 */
public class ManageStockJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private UserAccount userAcc;
    private EcoSystem business;
    private Organization organization;
    private Enterprise enterprise;
    private boolean ValidItemName;

    /**
     * Creates new form ManageStockJPanel
     */

    ManageStockJPanel(JPanel userProcessContainer, Organization organization, EcoSystem business, Enterprise enterprise, UserAccount account) {
       initComponents();
        this.organization=organization;
        this.enterprise=enterprise;
        this.account=account;
        this.business=business;
        this.userProcessContainer=userProcessContainer;
                populateTable();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Menu = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ProductNAME = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("PT Serif Caption", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 82));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Products  Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 40, 1200, 37));

        Menu.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        Menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Food Name"
            }
        ));
        jScrollPane1.setViewportView(Menu);
        if (Menu.getColumnModel().getColumnCount() > 0) {
            Menu.getColumnModel().getColumn(0).setResizable(false);
            Menu.getColumnModel().getColumn(1).setResizable(false);
            Menu.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 91));

        jLabel3.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Item Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 100, 30));

        ProductNAME.setMinimumSize(new java.awt.Dimension(7, 25));
        ProductNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ProductNAMEKeyReleased(evt);
            }
        });
        add(ProductNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 150, 30));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        back.setText(" Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 100, 40));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 80, 40));
    }// </editor-fold>//GEN-END:initComponents
    
    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) Menu.getModel();
        dtm.setRowCount(0);
      
        for(Products store:enterprise.getItemsList()) {
            Object row[] = new Object[1];
            row[0] = store;
            dtm.addRow(row);
        }
    }
    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
       
            
        for(Products p:enterprise.getItemsList()) 
        {
          if(ProductNAME.getText().equals(p.getItemName()))
          {
                
           JOptionPane.showMessageDialog(null, "Item already exists.","Error",JOptionPane.ERROR_MESSAGE);
           return;
           } 
        }
        if(ProductNAME.getText().equals("")||ProductNAME.getText()==null){
              JOptionPane.showMessageDialog(null, "Field(s) cannot be empty.","Error",JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        String name = ProductNAME.getText();
        Products s = enterprise.createMenuItem();
        s.setItemName(name);
        JOptionPane.showMessageDialog(null, "Item added","Success",JOptionPane.INFORMATION_MESSAGE);
        populateTable();
        ProductNAME.setText("");  
    }//GEN-LAST:event_addActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
                  int selectedRow = Menu.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a row.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            Products item = (Products)Menu.getValueAt(selectedRow, 0);
           enterprise.deleteItem(item);
        JOptionPane.showMessageDialog(null, "Item deleted.","Success",JOptionPane.INFORMATION_MESSAGE);
        populateTable();
    } 
    }//GEN-LAST:event_deleteActionPerformed

    private void ProductNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProductNAMEKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductNAMEKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Menu;
    private javax.swing.JTextField ProductNAME;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
