/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Component;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ashwin
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network n;
    private boolean nameValid;
    private int entAvail = 0;
    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateTable();
        populateComboF();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) entTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = network.getName();
                row[2] = enterprise.getEnterpriseType().getValue();

                model.addRow(row);
            }
        }
    }
    
      private boolean cityPatternCorrect(String val){
        Pattern p = Pattern.compile("^[a-zA-Z]+$");
        Matcher m = p.matcher(val);
        boolean b = m.matches();
        return b;
    }
      
    private void populateComboF() {
        NtwComboBox.removeAllItems();
        EntComboBox.removeAllItems();

        for (Network network : system.getNetworkList()) {
            NtwComboBox.addItem(network); 
        }
         for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
                EntComboBox.addItem(type); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        NtwComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EntComboBox = new javax.swing.JComboBox();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        success = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(entTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 74, 523, 95));

        jLabel1.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Network:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 215, 88, -1));

        NtwComboBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        NtwComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NtwComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NtwComboBoxActionPerformed(evt);
            }
        });
        add(NtwComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 211, 190, 30));

        jLabel2.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Enterprise Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 301, 130, -1));

        NameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NameFieldKeyReleased(evt);
            }
        });
        add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 297, 190, 30));

        jLabel3.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Enterprise Type:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 258, -1, -1));

        EntComboBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        EntComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        EntComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntComboBoxActionPerformed(evt);
            }
        });
        add(EntComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 254, 190, 30));

        submit.setBackground(new java.awt.Color(255, 255, 255));
        submit.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 101, 41));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        back.setText(" Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, -1, 30));

        jLabel4.setFont(new java.awt.Font("PT Serif Caption", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(80, 80, 82));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MANAGE ENTERPRISE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 723, 30));

        success.setText("Only text allowed");
        add(success, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        Network network = (Network) NtwComboBox.getSelectedItem();
                    for(Enterprise e: network.getEnterpriseDirectory().getEnterpriseList() ){
                       if(e.getEnterpriseType().equals(EntComboBox.getSelectedItem())){
                           entAvail = 1;
                       }
               }
       
        if(nameValid && entAvail != 1){
            Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) EntComboBox.getSelectedItem();

            if (network == null || type == null) {
                JOptionPane.showMessageDialog(null, "Invalid Input!");
                return;
            }

            String name = NameField.getText();
            Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);  
            n = network;
            success.setVisible(false);
            populateTable();
            NameField.setText("");
        }else {
            if(entAvail == 1){
                JOptionPane.showMessageDialog(null, "Enterprise is already added","Alert",JOptionPane.INFORMATION_MESSAGE);
                success.setVisible(false);
                NameField.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Required fields are not filled properly","Error",JOptionPane.ERROR_MESSAGE);
            }
           
        }

    }//GEN-LAST:event_submitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backActionPerformed

    private void NtwComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NtwComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NtwComboBoxActionPerformed

    private void EntComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntComboBoxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_EntComboBoxActionPerformed

    private void NameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameFieldKeyReleased
        // TODO add your handling code here:
        if(!cityPatternCorrect(NameField.getText()) && !(NameField.getText().isEmpty())){
            success.setVisible(true);
            nameValid = false;
        }else if(NameField.getText().isEmpty()){
            success.setVisible(false);
            nameValid = false;
        }else{
            success.setVisible(false);
            nameValid = true;
        }
    }//GEN-LAST:event_NameFieldKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox EntComboBox;
    private javax.swing.JTextField NameField;
    private javax.swing.JComboBox NtwComboBox;
    private javax.swing.JButton back;
    private javax.swing.JTable entTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submit;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables
}
