/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.QualityAssurance;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.QualityAssuranceEnterprise;
import Business.Network.Network;
import Business.Organisation.FoodAdvisorOrganisation;
//import Business.Organisation.InspectorOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodAdvWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author visha
 */
public class FoodAdvisorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FoodAdvisorJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network network;
    private UserAccount userAccount;
    Enterprise e;

    public FoodAdvisorJPanel(JPanel userProcessContainer, EcoSystem system, Network network,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system =system;
        this.network = network;
        this.userAccount = userAccount;
       // AdvisorTbl.getTableHeader().setDefaultRenderer(new tableHeaderColors());
        populateAdvTable();
    }
     private void populateAdvTable() {
        DefaultTableModel dtm = (DefaultTableModel) AdvisorTbl.getModel();
        dtm.setRowCount(0);
        Organisation org = null;
        for(Enterprise enter : network.getEnterpriseDirectory().getEnterpriseList()){
            if(enter instanceof QualityAssuranceEnterprise){
                e = enter;
            }
        }
        for (Organisation organisation : e.getOrganisationDirectory().getOrganisationList()){
            if (organisation instanceof FoodAdvisorOrganisation){
                org = organisation;
                break;
            }
        }
        if (org!=null){
            for(WorkRequest request: org.getWorkQueue().getWorkRequestList()) {
            if(request.getSender().equals(userAccount)){
            Object row[] = new Object[5];
            row[0] = request.getRequestID();
            row[1] = request.getMessage();
            row[2] = request.getReceiver();
            row[3] = ((FoodAdvWorkRequest)request).getFoodadvResult();
            row[4] = request.getStatus();
            dtm.addRow(row);
            }
    }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DoubtText = new javax.swing.JTextArea();
        SubmitBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AdvisorTbl = new javax.swing.JTable();

        jLabel1.setText("Food Advisor");

        jLabel2.setText("Ask Question:");

        DoubtText.setColumns(20);
        DoubtText.setRows(5);
        DoubtText.setText("DoubtText");
        jScrollPane1.setViewportView(DoubtText);

        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        AdvisorTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Doubt", "Advisor Name", "Information", "Status"
            }
        ));
        jScrollPane2.setViewportView(AdvisorTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(SubmitBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(SubmitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        if(userAccount.getWorkQueue().getWorkRequestList().size()== 0){
        FoodAdvWorkRequest request = new FoodAdvWorkRequest();
        request.setSender(userAccount);
        request.setMessage(DoubtText.getText());
        request.setStatus("Request sent to Admin");
        Organisation org = null;
        
        for(Enterprise enterp : network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterp instanceof QualityAssuranceEnterprise){
                e = enterp;
            }
        }
        for (Organisation organisation : e.getOrganisationDirectory().getOrganisationList()){
            if (organisation instanceof FoodAdvisorOrganisation){
                org = organisation;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null,"Request has been sent. You will receive an email once it is processed!!","Success",JOptionPane.INFORMATION_MESSAGE);
        populateAdvTable();
    }
    else{
            int x = userAccount.getWorkQueue().getWorkRequestList().size()-1;
            WorkRequest r = userAccount.getWorkQueue().getWorkRequestList().get(x);
            if(r.getStatus().toLowerCase().equals("result posted")){
                FoodAdvWorkRequest request = new FoodAdvWorkRequest();
                request.setSender(userAccount);
                request.setMessage(DoubtText.getText());
                request.setStatus("Request sent to Admin");
                Organisation org = null;

                for(Enterprise enter : network.getEnterpriseDirectory().getEnterpriseList()){
                    if(enter instanceof QualityAssuranceEnterprise){
                        e = enter;
                    }
                }
                for (Organisation organisation : e.getOrganisationDirectory().getOrganisationList()){
                    if (organisation instanceof QualityAssuranceEnterprise){
                        org = organisation;
                        break;
                    }
                }
                if (org!=null){
                    org.getWorkQueue().getWorkRequestList().add(request);
                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                }
                JOptionPane.showMessageDialog(null,"Request has been sent. You will receive an email once it is processed!!","Success",JOptionPane.INFORMATION_MESSAGE);
                populateAdvTable();
            }
            else {
                JOptionPane.showMessageDialog(null,"Please wait until the previous request has been processed !","Alert",JOptionPane.WARNING_MESSAGE);
            }
        } 
                           
    }//GEN-LAST:event_SubmitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AdvisorTbl;
    private javax.swing.JTextArea DoubtText;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
