/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import UserInterface.Receiver.CreateNewReceiverJPanel;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import static java.time.Clock.system;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author truptiraut
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    EcoSystem system;
    UserAccount account;
    Network network;
    Enterprise enterprise;
    Organisation organisation;
    /**
     * Creates new form MainJFrameCopy
     */
    public MainJFrame() {
        initComponents();
         system = dB4OUtil.retrieveSystem();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        panel1 = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        userNameTextField = new javax.swing.JTextField();
        usernameJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        passwordTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        SignUp = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        SplitPane.setDividerLocation(150);
        SplitPane.setDividerSize(21);

        panel1.setBackground(new java.awt.Color(186, 108, 44));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        panel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 104, -1));
        panel1.add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 127, -1));

        usernameJLabel.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        usernameJLabel.setText("UserName");
        panel1.add(usernameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 132, 34));

        passwordJLabel.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        passwordJLabel.setText("Password");
        panel1.add(passwordJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 171, 132, 34));

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        panel1.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 104, -1));

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        panel1.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 132, -1));

        jLabel1.setFont(new java.awt.Font("PT Serif Caption", 1, 14)); // NOI18N
        jLabel1.setText("New User?");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 433, -1, -1));

        SignUp.setText("Sign Up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        panel1.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 464, -1, -1));

        SplitPane.setLeftComponent(panel1);

        panel2.setBackground(new java.awt.Color(215, 200, 174));
        panel2.setForeground(new java.awt.Color(255, 204, 102));
        panel2.setAutoscrolls(true);
        panel2.setLayout(new java.awt.CardLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Thanks.jpeg"))); // NOI18N
        panel2.add(jLabel2, "card2");

        SplitPane.setRightComponent(panel2);

        getContentPane().add(SplitPane, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:

        String userName = userNameTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordTextField.getPassword();
        String password = String.valueOf(passwordCharArray);
        
        //Step1: Check in the system admin user account directory if you have the user
        UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);
        Enterprise enterprise =null;
        Organisation organization=null;
        
        if(userAccount==null){
            //Step 2: Go inside each network and check each enterprise
            for(Network network:system.getNetworkList()){
                //Step 2.a: check against each enterprise
                for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
                    userAccount=e.getUserAccountDirectory().authenticateUser(userName, password);
                    if(userAccount==null){
                       //Step 3:check against each organization for each enterprise
                       for(Organisation org:e.getOrganisationDirectory().getOrganisationList()){
                           userAccount=org.getUserAccountDirectory().authenticateUser(userName, password);
                           if(userAccount!=null){
                               enterprise = e;
                               organisation=org;
                               break;
                           }
                       }
                        
                    }
                    else{
                       enterprise = e;
                       break;
                    }
                    if(organization!=null){
                        break;
                    }  
                }
                if(enterprise!=null){
                    break;
                }
            }
        }
        if(userAccount !=null && userAccount.getReceiver() != null){
            network = userAccount.getReceiver().getNetwork();
        
        }
        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }
        else{
            CardLayout layout=(CardLayout)panel2.getLayout();
            panel2.add("workArea",userAccount.getRole().createWorkArea(panel2, enterprise, organisation,userAccount , system, network));
            layout.next(panel2);
        }
        
        loginButton.setEnabled(false);
        logoutButton.setEnabled(true);
        userNameTextField.setEnabled(false);
        passwordTextField.setEnabled(false);
        SignUp.setVisible(false);

    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
       
        logoutButton.setEnabled(false);
        userNameTextField.setEnabled(true);
        passwordTextField.setEnabled(true);
        loginButton.setEnabled(true);
        //orangeLbl.setEnabled(true);
        SignUp.setVisible(true);

        userNameTextField.setText("");
        passwordTextField.setText("");

        panel2.removeAll();
       SplitPane.setLeftComponent(panel1);

        panel2.setLayout(new java.awt.CardLayout());

        //orangeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/images/orangesBackground.jpg"))); // NOI18N
       
       // panel2.add(orangeLbl, "card2");
        SplitPane.setRightComponent(panel2);
        getContentPane().add(SplitPane, "card2");
        pack();
        SplitPane.setDividerLocation(300);
        dB4OUtil.storeSystem(system);

    }//GEN-LAST:event_logoutButtonActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
        System.out.println("user list  " + system.getUserAccountDirectory().getUserAccountList());
        CreateNewReceiverJPanel createCus =new CreateNewReceiverJPanel(panel2, system);
        panel2.add("SignUpJPanel",createCus);
        CardLayout layout=(CardLayout)panel2.getLayout();
        layout.next(panel2);
    }//GEN-LAST:event_SignUpActionPerformed
public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
   
//    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignUp;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel usernameJLabel;
    // End of variables declaration//GEN-END:variables
}
